BEGIN;
CREATE TABLE "brackets_contestants" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "fifa_team_id" integer NOT NULL REFERENCES "brackets_fifateam" ("id"), "player_1_id" integer NOT NULL REFERENCES "auth_user" ("id"), "player_2_id" integer NULL REFERENCES "auth_user" ("id"), "player_3_id" integer NULL REFERENCES "auth_user" ("id"), "player_4_id" integer NULL REFERENCES "auth_user" ("id"));
CREATE TABLE "brackets_fixtures" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(180) NOT NULL UNIQUE, "description" varchar(180) NULL, "date_created" datetime NOT NULL, "date_updated" datetime NOT NULL);
CREATE TABLE "brackets_fixturetype" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL UNIQUE);
CREATE TABLE "brackets_match__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "match_date" datetime NULL, "contestant_two_score" integer NULL);
INSERT INTO "brackets_match__new" ("contestant_two_score", "match_date", "id") SELECT "contestant_two_score", "match_date", "id" FROM "brackets_match";
DROP TABLE "brackets_match";
ALTER TABLE "brackets_match__new" RENAME TO "brackets_match";
CREATE INDEX "brackets_contestants_2079ec3b" ON "brackets_contestants" ("fifa_team_id");
CREATE INDEX "brackets_contestants_f0de2a95" ON "brackets_contestants" ("player_1_id");
CREATE INDEX "brackets_contestants_e55e16c9" ON "brackets_contestants" ("player_2_id");
CREATE INDEX "brackets_contestants_46b1be6c" ON "brackets_contestants" ("player_3_id");
CREATE INDEX "brackets_contestants_d18e62fd" ON "brackets_contestants" ("player_4_id");
CREATE TABLE "brackets_match__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "match_date" datetime NULL);
INSERT INTO "brackets_match__new" ("match_date", "id") SELECT "match_date", "id" FROM "brackets_match";
DROP TABLE "brackets_match";
ALTER TABLE "brackets_match__new" RENAME TO "brackets_match";
CREATE TABLE "brackets_match__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT);
INSERT INTO "brackets_match__new" ("id") SELECT "id" FROM "brackets_match";
DROP TABLE "brackets_match";
ALTER TABLE "brackets_match__new" RENAME TO "brackets_match";
CREATE TABLE "brackets_match__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "Match Complete" bool NOT NULL);
INSERT INTO "brackets_match__new" ("Match Complete", "id") SELECT 0, "id" FROM "brackets_match";
DROP TABLE "brackets_match";
ALTER TABLE "brackets_match__new" RENAME TO "brackets_match";
CREATE TABLE "brackets_match__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "Match Complete" bool NOT NULL, "Match Date" date NULL);
INSERT INTO "brackets_match__new" ("Match Complete", "Match Date", "id") SELECT "Match Complete", NULL, "id" FROM "brackets_match";
DROP TABLE "brackets_match";
ALTER TABLE "brackets_match__new" RENAME TO "brackets_match";
CREATE TABLE "brackets_match__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "Match Complete" bool NOT NULL, "Match Date" date NULL, "Team 1 Score" integer NULL);
INSERT INTO "brackets_match__new" ("Match Complete", "Match Date", "Team 1 Score", "id") SELECT "Match Complete", "Match Date", 0, "id" FROM "brackets_match";
DROP TABLE "brackets_match";
ALTER TABLE "brackets_match__new" RENAME TO "brackets_match";
CREATE TABLE "brackets_match__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "Match Complete" bool NOT NULL, "Match Date" date NULL, "Team 1 Score" integer NULL, "Team 2 Score" integer NULL);
INSERT INTO "brackets_match__new" ("Match Complete", "Match Date", "Team 1 Score", "id", "Team 2 Score") SELECT "Match Complete", "Match Date", "Team 1 Score", "id", 0 FROM "brackets_match";
DROP TABLE "brackets_match";
ALTER TABLE "brackets_match__new" RENAME TO "brackets_match";
CREATE TABLE "brackets_match__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "Match Complete" bool NOT NULL, "Match Date" date NULL, "Team 1 Score" integer NULL, "Team 2 Score" integer NULL, "contestant_1_at" varchar(1) NOT NULL);
INSERT INTO "brackets_match__new" ("Match Date", "Team 2 Score", "id", "contestant_1_at", "Match Complete", "Team 1 Score") SELECT "Match Date", "Team 2 Score", "id", 'H', "Match Complete", "Team 1 Score" FROM "brackets_match";
DROP TABLE "brackets_match";
ALTER TABLE "brackets_match__new" RENAME TO "brackets_match";
CREATE TABLE "brackets_fixtures__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(180) NOT NULL UNIQUE, "description" varchar(180) NULL, "date_created" datetime NOT NULL, "date_updated" datetime NOT NULL, "fixture_type_id" integer NOT NULL REFERENCES "brackets_fixturetype" ("id"));
INSERT INTO "brackets_fixtures__new" ("fixture_type_id", "id", "date_created", "date_updated", "name", "description") SELECT NULL, "id", "date_created", "date_updated", "name", "description" FROM "brackets_fixtures";
DROP TABLE "brackets_fixtures";
ALTER TABLE "brackets_fixtures__new" RENAME TO "brackets_fixtures";
CREATE INDEX "brackets_fixtures_ba84f98a" ON "brackets_fixtures" ("fixture_type_id");
CREATE TABLE "brackets_match__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "Match Complete" bool NOT NULL, "Match Date" date NULL, "Team 1 Score" integer NULL, "Team 2 Score" integer NULL, "contestant_1_at" varchar(1) NOT NULL, "contestant_1_id" integer NULL REFERENCES "brackets_contestants" ("id"));
INSERT INTO "brackets_match__new" ("contestant_1_id", "Match Date", "Team 2 Score", "id", "contestant_1_at", "Match Complete", "Team 1 Score") SELECT NULL, "Match Date", "Team 2 Score", "id", "contestant_1_at", "Match Complete", "Team 1 Score" FROM "brackets_match";
DROP TABLE "brackets_match";
ALTER TABLE "brackets_match__new" RENAME TO "brackets_match";
CREATE INDEX "brackets_match_a8530540" ON "brackets_match" ("contestant_1_id");
CREATE TABLE "brackets_match__new" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "Match Complete" bool NOT NULL, "Match Date" date NULL, "Team 1 Score" integer NULL, "Team 2 Score" integer NULL, "contestant_1_at" varchar(1) NOT NULL, "contestant_1_id" integer NULL REFERENCES "brackets_contestants" ("id"), "contestant_2_id" integer NULL REFERENCES "brackets_contestants" ("id"));
INSERT INTO "brackets_match__new" ("contestant_1_id", "Match Date", "Team 2 Score", "id", "contestant_1_at", "Match Complete", "Team 1 Score", "contestant_2_id") SELECT "contestant_1_id", "Match Date", "Team 2 Score", "id", "contestant_1_at", "Match Complete", "Team 1 Score", NULL FROM "brackets_match";
DROP TABLE "brackets_match";
ALTER TABLE "brackets_match__new" RENAME TO "brackets_match";
CREATE INDEX "brackets_match_a8530540" ON "brackets_match" ("contestant_1_id");
CREATE INDEX "brackets_match_5dea5cbb" ON "brackets_match" ("contestant_2_id");

COMMIT;
